{% set name = "dominate" %}
{% set version = "2.6.0" %}
{% set compress_type = "tar.gz" %}
{% set hash_val = "76ec2cde23700a6fc4fee098168b9dee43b99c2f1dd0ca6a711f683e8eb7e1e4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash_val }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - dominate

about:
  home: http://github.com/Knio/dominate/
  license: LGPL 3.0
  license_file: LICENSE.txt
  license_family: LGPL
  summary: Dominate is a Python library for creating and manipulating HTML documents using an elegant DOM API.
  dev_url: http://github.com/Knio/dominate/

extra:
  recipe-maintainers:
    - pmlandwehr
