{% set name = "dominate" %}
{% set version = "2.3.1" %}
{% set compress_type = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "4b8ce6f33633c9dd9175b228d21c00c801b6bd0327747cd5e17fc2da934c3a69" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python

  run:
    - python

test:
  imports:
    - dominate

about:
  home: http://github.com/Knio/dominate/
  license: LGPL 3.0
  license_file: LICENSE.txt
  license_family: LGPL
  summary: 'Dominate is a Python library for creating and manipulating HTML documents using an elegant DOM API.'
  dev_url: http://github.com/Knio/dominate/

extra:
  recipe-maintainers:
    - pmlandwehr
