{% set name = "dominate" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b15791ebea432218543a1702d76ae45d2ff95ff994e52014b8686a69dad772fd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip

  run:
    - python >=3.6

test:
  imports:
    - dominate
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/Knio/dominate/
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  license_family: LGPL
  summary: Dominate is a Python library for creating and manipulating HTML documents using an elegant DOM API.
  dev_url: http://github.com/Knio/dominate/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
